name: MAIN CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: 
  build:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
      paths_result: ${{ steps.skip_check.outputs.paths_result }}
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 7
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'pnpm'
    - name: Install
      run: pnpm install
    - name: Test
      run: pnpm test
    - name: Build
      run: pnpm build
    - id: skip_check
      uses: fkirc/skip-duplicate-actions@v5
      with:
        paths_filter: |
          rust:
            paths:
              - ["packages/sql-parser/**/*"]
            backtracking: 0

  call-rust-workflow:
    needs: build
    if: ${{ !fromJSON(needs.build.outputs.paths_result).rust.should_skip }}
    uses: ./.github/workflows/RUST_BUILD.yml